services:
  - type: web
    name: tutorial-manager-backend
    env: php
    rootDir: backend/api
    buildCommand: "composer install --no-dev --optimize-autoloader"
    startCommand: "php -S 0.0.0.0:10000 -t public"
    envVars:
      - key: APP_ENV
        value: prod
      - key: APP_DEBUG
        value: 0
      - key: DATABASE_URL
        value: sqlite:///%kernel.project_dir%/var/app.db
